<?php
/**
 * AdminPageIcons
 *
 * AdminPageIcons module for ProcessWire 2.4
 * Copyright (C) 2014 by Maks Feltrin - pine3ree
 *
 */

class Pimpled extends WireData implements Module
{
    public static function getModuleInfo()
    {
        return array(
            'title'    => 'Pimpled',
            'version'  => 11,
            'summary'  => 'Add a pimple container to the fuel, i.e. a $pimple instance api variable in your template files',
            'author'   => 'pine3ree',
            'href'     => 'https://github.com/pine3ree/Pimpled',
            'singular' => true,
            'autoload' => function () {
                $page = wire('page');
                return!($page instanceof Page && $page->template == 'admin');
            },
        );
    }

    public function init()
    {
        $this->createContainer();
    }

    public function createContainer()
    {
        require_once __DIR__ . '/lib/PimpledContainer.php';

        $container = new PimpledContainer($this);

        $this->wire('pimple', $container);
        $this->wire('container', $container);
        $this->wire('ioc', $container);
        $this->wire('di', $container);
        $this->wire('locator', $container);

        return $container;
    }

    public function ___install() {

		if (version_compare(PHP_VERSION, '5.3.8', '<')) {
			throw new WireException("This module requires PHP 5.3.8 or newer.");
		}

        $version = 100 * ProcessWire::versionMajor
            + 10 * ProcessWire::versionMinor
            + 1 * ProcessWire::versionRevision
        ;

        if($version < 250) {
			throw new WireException("This module requires ProcessWire 2.5.0 or newer.");
		}
	}

}
