<?php
/**
 * Pimpled
 *
 * Pimple dependency injection container and service locator for ProcessWire 2.5
 *
 * @author maks feltrin - pine3ree
 * @copyright 2014 pine3ree
 */

class Pimpled extends WireData implements Module
{
    public static function getModuleInfo()
    {
        return array(
            'title'    => 'Pimpled',
            'version'  => 12,
            'summary'  => 'Add a pimple container to the fuel, i.e. a $pimple instance api variable in your template files',
            'author'   => 'pine3ree',
            'href'     => 'https://github.com/pine3ree/Pimpled',
            'singular' => true,
            'autoload' => function () {
                $page = wire('page');
                return!($page instanceof Page && $page->template == 'admin');
            },
        );
    }

    public function init()
    {
        $this->createContainerApi();
    }

    protected function createContainerApi()
    {
        $container = $this->createContainer();

        $this->wire('pimple', $container);
        $this->wire('container', $container);
        $this->wire('ioc', $container);
        $this->wire('di', $container);
        $this->wire('locator', $container);
    }

    public function createContainer()
    {
        require_once __DIR__ . '/lib/PimpledContainer.php';

        return new PimpledContainer($this);
    }

    public function ___install() {

		if (version_compare(PHP_VERSION, '5.3.8', '<')) {
			throw new WireException("This module requires PHP 5.3.8 or newer.");
		}

        $pwVersion = 100 * ProcessWire::versionMajor
            + 10 * ProcessWire::versionMinor
            + 1 * ProcessWire::versionRevision
        ;

        if ($pwVersion < 250) {
			throw new WireException("This module requires ProcessWire 2.5.0 or newer.");
		}
	}

}
